name: Build and test

on: [push, pull_request]

env:
  ASAN_OPTIONS: detect_stack_use_after_return=1:color=always
  UBSAN_OPTIONS: print_stacktrace=1:color=always
  OMP_NUM_THREADS: 1

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install igraph dependencies
        run: sudo apt-get install libglpk-dev libarpack2-dev

      - name: Build igraph
        run: |
          wget https://github.com/igraph/igraph/releases/download/0.10.13/igraph-0.10.13.tar.gz
          tar xfz igraph-0.10.13.tar.gz
          cd igraph-0.10.13
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/local
          cmake --build . --parallel
          cmake --install .

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create build environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configuration
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_PREFIX_PATH=$HOME/local -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -g -fno-omit-frame-pointer"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --parallel

      - name: Test
        run: ctest -j $(nproc) --output-on-failure --timeout 180
        working-directory: ${{github.workspace}}/build
